### ISSUE TITLE
FileSystemException: Cannot rename file to '{workspace}\main.dart.d13cc257.js', path = '{workspace}\main.dart.js' (OS Error: 另一个程序正在使用此文件，进程无法访问

### ISSUE THREAD

**Issue by slowfall** [TryImpossible/flutter_web_optimizer#11]
### 错误信息
```
> Unhandled exception:
> FileSystemException: Cannot rename file to '{workspace}\main.dart.d13cc257.js', path = '{workspace}\main.dart.js' (OS Error: 另一个程序正在使用此文件，进程无法访问。  
> , errno = 32)
> #0      _File.throwIfError (dart:io/file_impl.dart:635:7)
> #1      _File.renameSync (dart:io/file_impl.dart:320:5)
> #2      OptimizeCommand._hashAssets.<anonymous closure> (package:flutter_web_optimizer/src/optimize/optimize_command.dart:511:17)
> #3      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:617:13)
> #4      OptimizeCommand._hashAssets (package:flutter_web_optimizer/src/optimize/optimize_command.dart:510:16)
> #5      OptimizeCommand.run (package:flutter_web_optimizer/src/optimize/optimize_command.dart:107:5)
> <asynchronous suspension>
> #6      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
> <asynchronous suspension>
```

### 运行环境
`Dart SDK version: 2.18.6 (stable) (Tue Dec 13 21:15:14 2022 +0000) on "windows_x64"`

### 错误原因
是代码 lib/src/optimize/optimize_command.dart 中的函数 _splitMainDartJS 在文件 'main.dart.js' 打开之后，没有关闭导致的。
https://github.com/TryImpossible/flutter_web_optimizer/blob/d7937703ecab7b1de378035bb835f5a0898a2088/lib/src/optimize/optimize_command.dart#L291

### 解决
代码改成如下，应该就能解决了
```
    final raf = file.openSync(mode: FileMode.append);
    raf.writeStringSync('\n\n//@ sourceURL=main.dart.js\n');
    raf.closeSync();
```
### 疑问
main.dart.js 已经被拆分了，该文件是否应该不再需要了呢？

**Comment by Dynesshely** [comment]
我也遇到了这个问题, 最新的 1.1.10 版本的包中仍然存在这个问题, 希望能够尽快修复, 万分感谢!

**Comment by TryImpossible** [comment]
@slowfall @Dynesshely ,这个问题复现在windows平台上，已经发布了1.1.11版本

**Comment by TryImpossible** [comment]
@slowfall ,关于main.dart.js保留是因为当web构建时默认开启了source-map，当发生异常进行source-map解析时需要用到main.dart.js原文件，否则无法解析到具体哪行代码产生的错误。如何你使用了sentry，应该会遇到此问题

**Comment by Raviteja11122** [comment]
@TryImpossible looks like working in 1.1.11, I'll try out. If possible try to add issue number in the new release change log.

**Comment by Dynesshely** [comment]
Tested today with spare time, in ^1.1.12, this problem was solved perfectly!
Thanks.
