### ISSUE TITLE
Uncaught TypeError: v.startsWith is not a function

### ISSUE THREAD

**Issue by LeeCareFree** [TryImpossible/flutter_web_optimizer#15]
使用插件处理后，报这个错误，麻烦帮忙看看为啥？
// 具体报错信息
main.dart.f6e870ae.js:3667 Uncaught TypeError: v.startsWith is not a function
    at HTMLScriptElement.set (flutter_web_optimizer.625c451a.js:178:19)
    at Object.bl9 (main.dart.f6e870ae.js:23667:6)
    at aVP.$0 (main.dart.f6e870ae.js:108827:7)
    at main.dart.f6e870ae.js:46311:33
    at aUQ.a (main.dart.f6e870ae.js:4847:63)
    at aUQ.$2 (main.dart.f6e870ae.js:41142:14)
    at Object.a1 (main.dart.f6e870ae.js:4833:11)
    at aW5.$0 (main.dart.f6e870ae.js:46316:10)
    at main.dart.f6e870ae.js:30923:19
    at aUQ.a (main.dart.f6e870ae.js:4847:63)
// 具体代码段
Object.defineProperty(element, property, {
          get: function () {
            return value;
          },
          set: function (v) {
            value = v;
            if (v.startsWith('./')) {
              v = v.replace('./', '');
            }
            if (hashFileManifest[v]) {
              value = assetBase + hashFileManifest[v];
            }
            element.setAttribute(property, value);
          }
        })

**Comment by TryImpossible** [comment]
@LeeCareFree ,已发布1.1.12版本，可以帮忙看看是否修复
