### ISSUE TITLE
caught TypeError: Aa.indexOf is not a function  

### ISSUE THREAD

**Issue by liyingte998** [TryImpossible/flutter_web_optimizer#17]
in.dart.e2b04c5b.js:3024 Uncaught TypeError: Aa.indexOf is not a function
    at canvaskit.js:154:292
    at main.dart.e2b04c5b.js:197:18
    at cEY.a (main.dart.e2b04c5b.js:4311:62)
    at cEY.$2 (main.dart.e2b04c5b.js:66357:14)
    at cDv.$1 (main.dart.e2b04c5b.js:66351:21)
    at aSm.a6u (main.dart.e2b04c5b.js:67562:34)
    at cnE.$0 (main.dart.e2b04c5b.js:66812:11)
    at Object.a0Z (main.dart.e2b04c5b.js:4456:40)
    at b5.vh (main.dart.e2b04c5b.js:66735:3)
    at cnw.$0 (main.dart.e2b04c5b.js:66779:13)
n

是否不支持--web-renderer canvaskit？因为当--web-renderer html运行良好。

**Comment by TryImpossible** [comment]
@liyingte998 ,暂有没有支持canvaskit模式
